from randomWordGenerator import generateWord
basics1 = [

    "screed",
    "hound",
    "err",
    "dupe",
    "inflammatory",
    "telltale",
    "pinnacle",
    "bleak",
    "outlook",
    "demure",
    "modest",
    "stipend",
    "demean",
    "embroiled",
    "vindictive",
    "unnerve",
    "insolvent",
    "dogged",
    "spendthrift",
    "throughgoing",
    "slapdash",
    "underwrite",
    "amiable",
    "peruse",
    "indigenous",
    "zeninth",
    "variance",
    "affable",
    "diabolical",
    "wicked",
    "tender",
    "varacious",
    "miser",
    "pine",
    "yearn",
    "acme",
    "affluent",
    "erratic",
    "indict",
    "mesmerize",
    "spellbind",
    "indignant",
    "serendipity",
    "tirade",
    "remiss",
    "profuse",
    "abundance",
    "inundate",
    "macarbe",
    "reprobate",
    "candid"

]

generateWord(basics1)