from randomWordGenerator import generateWord
basic4 = [
    # "buck",
    # "tumult",
    # "inadvertent",
    # "jargon",
    # "fickle",
    # "debase",
    # "pertinent",
    # "perpetutate",
    # "dertimental",
    # "martial",
    "augment",
    "impeccable",
    "assuage",
    "urbane",
    "irresolute",
    "tawdry",
    "assail",
    "facetious",
    "genteel",
    "unruly",
    "cornucopia",
    # "illicit",
    # "altruism",
    # "grovel",
    # "credence",
    # "uncompromising",
    # "benign",
    # "conducive",
    # "sentimental",
    # "smattering",
    "perennial",
    "elaborate",
    "banish",
    "glib",
    "contemptuous",
    "hamstrung",
    "whimsical",
    "spurn",
    "empathetic",
]

generateWord(basic4)
